# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kasra Amani
title: Undergraduate Student - Computer Engineering
email: kasraamani2001@gmail.com
website: www.kasraamani.com

# Dark Mode (true/false/never)
darkmode: true

# Social links (You can update or remove these as needed)
#twitter_username: facespics
github_username:  iTskAsra
linkedin_username: kasra-amani-99b91b196

# Additional icon links (You can update or remove these as needed)
additional_links:
- title: dasham Daviran
  icon: fas fa-globe
  url: https://www.mohammadrezadaviran.me

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  I am a Masters student in Computer Science at Technical University of Darmstadt, and received my Bachelor of Science in Computer Engineering from Sharif. My main research interests are Cloud and Edge Computing, IoT, Computer Networks and Cyber-Security and Embedded Computing.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Advanced Programming
        description: Our team, consisting of me and two teammates, developed an online shopping tool. This web-based application boasts an intuitive UI and functional features.
      - layout: top-middle
        title: Embedded Systems
        description: Developed a smart water container equipped with a proximity sensor to detect user requests. Additionally, it utilizes water level sensors to monitor the water supply's level.
      - layout: top-middle
        title: Computer Simulations
        description: Developed a discrete event simulator that schedules tasks on a CPU. The simulator employs a two-layer structure for efficient task management.
      - layout: top-middle
        title: Operating Systems
        description: As part of a four-member team, we undertook the challenging CS162 course project from Berkeley. This involved enhancing and adding numerous features to PintOS, a basic operating system specifically designed for this course.
      - layout: top-middle
        title: Design of Programming Languages
        description: Our team designed and implemented an interpreter for a language resembling Python, utilizing Racket for the development process.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Quera
        role: Student
        description: Enrolled in a comprehensive PHP course offered by Quera, a prominent online platform for Iranian developers.
      - layout: left
        title: Sharif University of Technology
        role: Intern
        description: I started my work in Prof. Ansari's Cyber-Physical Lab and was first working on a new scheduling algorithm for embedded devices using the gem5 simulator. The nature of the project later changed entirely and I am now working on a novel resource allocation and scheduling policy in the context of fog computing.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Technical University of Darmstadt
        caption: 2025 - Ongoing
        sub_title: Master of Science in Computer Science
        description: Pursuing a M.Sc. in Computer Science at Technical University of Darmstadt
      - layout: left
        title: Sharif University of Technology
        caption: 2019 - 2024
        sub_title: Bachelor of Science in Computer Engineering (CE)
        description: Received my B.Sc. in Computer Engineering at Sharif University of Technology, one of the premier institutions in the region. Achieved a commendable GPA of 16.16/20, reflecting dedication and academic excellence.
      - layout: left
        title: Shahid Ejeyi Highschool, Organization of Exceptional Talents
        caption: 2016 - 2019
        sub_title: High School Diploma
        description: Completed high school education at Shahid Ejeyi Highschool under the Organization of Exceptional Talents. Graduated with an outstanding GPA of 19.54/20, showcasing academic prowess and commitment.

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming, with a particular fondness for Counter Strike
      - Violin, with 14 years of experience and a keen interest in Baroque era music

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
